config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  root 'products#index'

  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  resources :sessions, only: [:create]
  get '/signup' => 'users#new'
  get '/my_account' => 'users#edit'
  resource :user, only: [:create, :update] do
    member do
      get 'password'
      patch 'update_password'
      post 'update_password'
    end
  end

  concern :buyable do
    get 'buy' => 'line_items#new'
  end

  resources :charges, only: [:index, :show] do
    member do
      post 'refund'
      patch 'refund'
    end
  end

  resources :postage_services, except: [:show] do
    resources :postage_costs, only: [:new]
  end

  resources :products do
    concerns :buyable
    resources :stock_levels, only: [:index, :new, :create]
    resources :sub_products, only: [:index, :new]
    resources :allocations, only: [:index]
  end

  resources :gift_card_products, only: :index do
    concerns :buyable
  end

  resources :gift_card_products, only: :show, controller: :products

  resources :gift_cards, only: [:index] do
    collection do
      get :redeem
      post :allocate
      patch :allocate
    end
  end

  resources :stock_levels, only: [:destroy, :edit, :update] do
    resources :orders, only: [:index], module: :seller
    resources :allocations, only: [:index]
  end

  resources :allocations, only: [:index]

  resources :images, only: [:show]

  resources :orders, except: [:destroy, :new, :create, :edit] do
    member do
      patch 'set_current'
      get 'pay'
      patch 'cancel'
    end
    resources :redemptions, only: [:create, :destroy], shallow: true
  end
  resource :cart, only: [:show, :destroy, :update] do
    patch 'confirm'
    patch 'update_address'
  end
  resources :carts, only: [:index]
  get '/checkout' => 'carts#checkout'

  resources :line_items, only: [:show, :create, :destroy, :update]
  resources :currencies, except: :show

  resources :addresses
  resources :postage_costs, except: :show

  namespace :seller do
    get '/allocations/:allocation_id/gift_cards' => 'gift_cards#index', as: :allocation_gift_cards
    resources :orders, only: [:index, :show, :update] do
      resources :gift_cards, only: :index
    end
    resources :products, only: [:index]
    resources :gift_card_products, except: :show
    resources :gift_cards, except: :show do
      resources :orders, only: :index
    end
    resources :users, only: [:index] do
      resources :gift_cards, only: :new
      resources :orders, only: :index
      get '/allocations' => '/allocations#index'
    end
  end
  

end

app/models/postage_service.rb
class PostageService < ActiveRecord::Base
  ## Relationships
  has_many :postage_costs, dependent: :destroy
  has_many :orders, dependent: :nullify

  ## Validations
  validates :name, presence: true, uniqueness: true

  ## Scopes
  scope :default, -> { where(default: true).first }

  #callbacks
  before_save :clear_defaults, if: -> { default? }


  private
    def clear_defaults
      #if we're setting this item to be default
      #we want to clear the flag from any other items
      defaults=self.class.where(default: true)
      defaults=defaults.where.not(id: id) if persisted?
      defaults.update_all(default: false)
    end
end

app/controllers/postage_services_controller.rb
class PostageServicesController < ApplicationController
  before_action :signed_in_seller
  before_action :find_postage_service, only: [:edit, :update, :destroy]

  def index
    @postage_services=PostageService.all
  end

  def new
    @postage_service=PostageService.new
  end

  def create
    @postage_service=PostageService.new(postage_service_params)
    if  @postage_service.save
      flash.now[:success]="Postage service created"
      respond_to do |format|
        format.html { flash.keep and redirect_to postage_services_path }
        format.js
      end
    else
      flash.now[:danger]="Postage service creation failed"
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @postage_service.update_attributes(postage_service_params)
      flash.now[:success]="Item updated"
      respond_to do |format|
        format.html { flash.keep and redirect_to postage_services_path }
        format.js
      end
    else
      flash.now[:danger]="Update failed"
      render 'edit'
    end
  end

  def destroy
    if @postage_service.destroy
      flash.now[:success]="Postage service removed"
      respond_to do |format|
        format.html { flash.keep and redirect_to postage_services_path }
        format.js
      end
    else
      flash.now[:danger]="Deletion failed"
      respond_to do |format|
        format.html { flash.keep and redirect_to postage_services_path }
        format.js { render partial: 'shared/refresh_flash' }
      end
    end
  end

  private
    def postage_service_params
      params.require(:postage_service).permit(:name, :default)
    end

    def find_postage_service
      @postage_service=PostageService.find(params[:id]) if params[:id]
    end
end

app/helpers/postage_services_helper.rb
module PostageServicesHelper
end

app/views/postage_services/_postage_service.html.erb
<div class="panel panel-default" id="<%= css_id(postage_service) %>">
	<div class="panel-heading">
		<%= postage_service.name %>
		<%= action_bar(postage_service, dropdown: true, remote: true) do |bar| %>
			<%= bar.item "New postage cost", new_postage_service_postage_cost_path(postage_service) %>
		<% end %>
	</div>
	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>From weight</th>
				<th>To weight</th>
				<th>Cost</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody id="costs_for_<%= css_id(postage_service) %>">
			<%= render postage_service.postage_costs %>
		</tbody>
	</table>
</div>

app/views/postage_services/_postage_service_form.html.erb
<%
options={}
options[:remote]=true if request.xhr?
%>
<%= form_for postage_service, options do |f| %>
	<%= render 'shared/form_error', object: f.object %>
	<div class="form-group">
		<%= f.label :name, class: "control-label" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="checkbox">
		<label>
			<%= f.check_box :default %>
			Default postage service
		</label>
	</div>
	<%= f.submit class: "btn btn-default" %>
<% end %>

app/views/postage_services/create.js.erb
jQuery("#postage_services").append("<%= escape_javascript(render 'postage_service', postage_service: @postage_service) %>");
<%= render 'shared/refresh_flash' %>
<%= render 'shared/hide_modal' %>

app/views/postage_services/destroy.js.erb
jQuery("#<%= css_id(@postage_service) %>").slideToggle(function() { jQuery(this).remove(); });
<%= render 'shared/refresh_flash' %>

app/views/postage_services/edit.html.erb
<%
provide(:title, "Edit postage service")
provide(:heading, "Edit postage service")
%>

<%= render 'postage_service_form', postage_service: @postage_service %>

app/views/postage_services/edit.js.erb
jQuery(".edit_postage_service").replaceWith("<%= escape_javascript(render 'postage_service_form', postage_service: @postage_service) %>");
<%= render 'shared/refresh_flash' %>

app/views/postage_services/index.html.erb
<% provide(:title, "Postage services") %>

<%= content_tag(:h1, "Postage services") %>


<%= link_to "New", new_postage_service_path, data: {modal_target: '#modal'}, class: "btn btn-default" %>

<div id="postage_services">
	<%= render @postage_services %>
</div>

app/views/postage_services/new.html.erb
<%
provide(:title, "New postage service")
provide(:heading, "New postage service")
%>

<%= render 'postage_service_form', postage_service: @postage_service %>

app/views/postage_services/new.js.erb
jQuery(".new_postage_service").replaceWith("<%= escape_javascript(render 'postage_service_form', postage_service: @postage_service) %>");
<%= render 'shared/refresh_flash' %>

app/views/postage_services/update.js.erb
jQuery("#<%= css_id(@postage_service) %>").replaceWith("<%= escape_javascript(render @postage_service) %>");
<%= render 'shared/refresh_flash' %>
<%= render 'shared/hide_modal' %>