config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  root 'products#index'

  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  resources :sessions, only: [:create]
  get '/signup' => 'users#new'
  get '/my_account' => 'users#edit'
  resource :user, only: [:create, :update] do
    member do
      get 'password'
      patch 'update_password'
      post 'update_password'
    end
  end

  concern :buyable do
    get 'buy' => 'line_items#new'
  end

  resources :charges, only: [:index, :show] do
    member do
      post 'refund'
      patch 'refund'
    end
  end

  resources :postage_services, except: [:show] do
    resources :postage_costs, only: [:new]
  end

  resources :products do
    concerns :buyable
    resources :stock_levels, only: [:index, :new, :create]
    resources :sub_products, only: [:index, :new]
    resources :allocations, only: [:index]
  end

  resources :gift_card_products, only: :index do
    concerns :buyable
  end

  resources :gift_card_products, only: :show, controller: :products

  resources :gift_cards, only: [:index] do
    collection do
      get :redeem
      post :allocate
      patch :allocate
    end
  end

  resources :stock_levels, only: [:destroy, :edit, :update] do
    resources :orders, only: [:index], module: :seller
    resources :allocations, only: [:index]
  end

  resources :allocations, only: [:index]

  resources :images, only: [:show]

  resources :orders, except: [:destroy, :new, :create, :edit] do
    member do
      patch 'set_current'
      get 'pay'
      patch 'cancel'
    end
    resources :redemptions, only: [:create, :destroy], shallow: true
  end
  resource :cart, only: [:show, :destroy, :update] do
    patch 'confirm'
    patch 'update_address'
  end
  resources :carts, only: [:index]
  get '/checkout' => 'carts#checkout'

  resources :line_items, only: [:show, :create, :destroy, :update]
  resources :currencies, except: :show

  resources :addresses
  resources :postage_costs, except: :show

  namespace :seller do
    get '/allocations/:allocation_id/gift_cards' => 'gift_cards#index', as: :allocation_gift_cards
    resources :orders, only: [:index, :show, :update] do
      resources :gift_cards, only: :index
    end
    resources :products, only: [:index]
    resources :gift_card_products, except: :show
    resources :gift_cards, except: :show do
      resources :orders, only: :index
    end
    resources :users, only: [:index] do
      resources :gift_cards, only: :new
      resources :orders, only: :index
      get '/allocations' => '/allocations#index'
    end
  end
  

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  validates :iso_code, presence: true, uniqueness: true, length: {is: 3}, format: {with: /\A[a-z]{3}\z/i, message: "Please use the three letter code, not the numeric code"}
  validates :symbol, presence: true
  validates :decimal_places, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  has_many :products, dependent: :nullify, inverse_of: :currency
  has_many :line_items, dependent: :nullify, inverse_of: :currency
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :signed_in_seller
  before_action :currency_from_params, only: [:edit, :update, :destroy]

  def index
    @currencies=Currency.all
  end

  def edit
  end

  def update
    if @currency.update_attributes(currency_params)
      flash.now[:success]="Currency updated"
      respond_to do |format|
        format.html { flash.keep and redirect_to currencies_url }
        format.js
      end
    else
      flash.now[:danger]="Update failed"
      render 'edit'
    end
  end

  def new
    @currency=Currency.new
  end

  def create
    @currency=Currency.new(currency_params)
    if @currency.save
      flash.now[:success]="New currency #{@currency.iso_code} created"
      respond_to do |format|
        format.html { flash.keep and redirect_to currencies_url }
        format.js
      end
    else
      flash.now[:danger]="Currency creation failed"
      render 'new'
    end
  end

  def destroy
    if @currency.destroy
      flash.now[:success]="Currency deleted"
      respond_to do |format|
        format.js
        format.html { flash.keep and redirect_to currencies_url}
      end
    else
      flash.now[:danger]="Currency deletion failed"
      respond_to do |format|
        format.html { flash.keep and redirect_to currencies_url }
        format.js { render partial: 'shared/refresh_flash' }
      end
    end
  end


  private
    def currency_from_params
      @currency=Currency.find(params[:id])
    end
    def currency_params
      params.require(:currency).permit(:iso_code, :symbol, :decimal_places)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_currency.html.erb
<div id="<%= css_id(currency) %>" class="row">
	<div class="col-md-1">
		<%= currency.iso_code %>
	</div>
	<div class="col-md-1">
		<%= currency.symbol %>
	</div>
	<div class="col-md-1">
		<%= currency.decimal_places %>
	</div>
	<div class="col-md-3">
		<%= action_bar(currency, vertical: false, remote: true, title: nil) %>
	</div>
</div>

app/views/currencies/_currency_form.html.erb
<%= form_for currency, remote: true, class: "form-inline" do|f| %>
<%= render 'shared/form_error', object: f.object %>
<div class="form-group">
	<%= f.label :iso_code, class: "control-label" %>
	<%= f.text_field :iso_code, class: "form-control" %>
	<p class="help-block">
		Three letter currency ISO code used to process payments (e.g.: GBP, USD).  Ensure you have the correct code or payment processing will fail. Check <a href="http://en.wikipedia.org/wiki/ISO_4217" target="_blank">ISO 4217</a> for a list of valid codes.
	</p>
</div>
<div class="form-group">
	<%= f.label :symbol, class: "control-label" %>
	<%= f.text_field :symbol, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :decimal_places, class: "control-label" %>
	<%= f.text_field :decimal_places, class: "form-control" %>
</div>
<%= f.submit class: "btn btn-default" %>
<% end %>

app/views/currencies/create.js.erb
//currency_new is the li with the form new_currency
jQuery(".currency_list").append("<%= escape_javascript(render @currency) %>");
<%= render 'shared/refresh_flash' %>
<%= render 'shared/hide_modal' %>

app/views/currencies/destroy.js.erb
jQuery("#<%= css_id(@currency) %>").slideToggle(function() { jQuery(this).remove(); });
<%= render 'shared/refresh_flash' %>

app/views/currencies/edit.html.erb
<% provide(:title, "Edit currency #{@currency.iso_code}") %>

<% provide(:heading, "Edit currency #{@currency.iso_code}") %>


<%= render 'currency_form', currency: @currency %>

app/views/currencies/edit.js.erb
jQuery(".edit_currency").replaceWith("<%= escape_javascript(render 'currency_form', currency: @currency) %>");
jQuery(".edit_currency [name='currency[iso_code]']").focus();
<%= render 'shared/focus_error', object: @currency %>

app/views/currencies/index.html.erb
<% provide(:title, "Currency maintenance") %>

<% provide(:heading, "Currency maintenance") %>

<div id="currency_new" class="row"><%= link_to "Create new", new_currency_path, data: {modal_target: '#modal'}, class: "btn btn-default" %></div>
<div class="currency_list">
	<%= render @currencies %>
</div>

app/views/currencies/new.html.erb
<% provide(:title, "New currency") %>

<% provide(:heading, "New currency") %>

<%= render 'currency_form', currency: @currency %>

app/views/currencies/new.js.erb
jQuery(".new_currency").replaceWith("<%= escape_javascript(render 'currency_form', currency: @currency) %>");
jQuery(".new_currency [name='currency[iso_code]']").focus();
<%= render 'shared/focus_error', object: @currency %>

app/views/currencies/update.js.erb
jQuery("#<%= css_id(@currency) %>").replaceWith("<%= escape_javascript(render @currency) %>");
<%= render 'shared/refresh_flash' %>
<%= render 'shared/hide_modal' %>