config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  root 'products#index'

  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  resources :sessions, only: [:create]
  get '/signup' => 'users#new'
  get '/my_account' => 'users#edit'
  resource :user, only: [:create, :update] do
    member do
      get 'password'
      patch 'update_password'
      post 'update_password'
    end
  end

  concern :buyable do
    get 'buy' => 'line_items#new'
  end

  resources :charges, only: [:index, :show] do
    member do
      post 'refund'
      patch 'refund'
    end
  end

  resources :postage_services, except: [:show] do
    resources :postage_costs, only: [:new]
  end

  resources :products do
    concerns :buyable
    resources :stock_levels, only: [:index, :new, :create]
    resources :sub_products, only: [:index, :new]
    resources :allocations, only: [:index]
  end

  resources :gift_card_products, only: :index do
    concerns :buyable
  end

  resources :gift_card_products, only: :show, controller: :products

  resources :gift_cards, only: [:index] do
    collection do
      get :redeem
      post :allocate
      patch :allocate
    end
  end

  resources :stock_levels, only: [:destroy, :edit, :update] do
    resources :orders, only: [:index], module: :seller
    resources :allocations, only: [:index]
  end

  resources :allocations, only: [:index]

  resources :images, only: [:show]

  resources :orders, except: [:destroy, :new, :create, :edit] do
    member do
      patch 'set_current'
      get 'pay'
      patch 'cancel'
    end
    resources :redemptions, only: [:create, :destroy], shallow: true
  end
  resource :cart, only: [:show, :destroy, :update] do
    patch 'confirm'
    patch 'update_address'
  end
  resources :carts, only: [:index]
  get '/checkout' => 'carts#checkout'

  resources :line_items, only: [:show, :create, :destroy, :update]
  resources :currencies, except: :show

  resources :addresses
  resources :postage_costs, except: :show

  namespace :seller do
    get '/allocations/:allocation_id/gift_cards' => 'gift_cards#index', as: :allocation_gift_cards
    resources :orders, only: [:index, :show, :update] do
      resources :gift_cards, only: :index
    end
    resources :products, only: [:index]
    resources :gift_card_products, except: :show
    resources :gift_cards, except: :show do
      resources :orders, only: :index
    end
    resources :users, only: [:index] do
      resources :gift_cards, only: :new
      resources :orders, only: :index
      get '/allocations' => '/allocations#index'
    end
  end
  

end

app/models/cart.rb
class Cart < Order
  validates :cart_token, presence: true, uniqueness: true

  before_validation :create_token


  #Our cart token just needs to be random enough that users won't try and guess other peoples carts
  #we won't encrypt this like we do the session remember token as it's not as important, plus it 
  #means we can re-use the token again if the user logs in from a different PC
  def self.new_cart_token
    SecureRandom.urlsafe_base64
  end


  private
    def create_token
      self.cart_token||=Cart.new_cart_token
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :signed_in_user, only: [:checkout, :confirm, :update_address]

  def show
    @cart=current_cart
  end

  def destroy
    if current_cart.user==current_user and current_cart.destroy
      flash[:success]="Cart cleared!"
    else
      flash[:danger]="Error removing cart"
    end
    self.current_cart=nil
    redirect_to root_url
  end

  def update
    @cart=current_cart
    #setting quantity to be zero should say destroy
    params[:cart][:line_items_attributes].each do |k,v|
      v[:_destroy]='1' if v[:quantity]=="0"
    end if params[:cart]
    if @cart.update_attributes(cart_params)
      if params[:commit]=="Checkout"
        respond_to do |format|
          format.html { redirect_to checkout_url }
          format.js { render 'redirect_to_checkout' }
        end
        return
      else
        flash.now[:success]="Cart updated"
      end
    else
      flash.now[:danger]="Couldn't update cart contents"
    end
    respond_to do |format|
      format.html { flash.keep and redirect_to cart_path }
      format.js { render 'show'}
    end
  end

  def checkout
    @cart=current_cart
    @cart.delivery||=OrderAddress.new(source_address: current_user.addresses.delivery.first)
    @cart.billing||=OrderAddress.new(source_address: current_user.addresses.billing.first)
  end

  def update_address
    @cart=current_cart
    @modes=address_params
    @cart.assign_attributes(address_params)
    @cart.billing.copy_address if address_params[:billing_attributes]
    @cart.delivery.copy_address if address_params[:delivery_attributes]
    if @cart.save
      flash.now[:success]="Address set"
    else
      flash.now[:danger]="Failed to set address"
    end
    respond_to do |format|
      format.html { redirect_to checkout_path}
      format.js
    end
  end

  def confirm
    @cart=current_cart
    if @cart.user and !current_user?(@cart.user)
      redirect_to root_url
      return
    end
    @cart.user=current_user
    @cart.delivery||=OrderAddress.new(source_address: current_user.addresses.delivery.first).copy_address
    @cart.billing||=OrderAddress.new(source_address: current_user.addresses.billing.first).copy_address
    @cart.status=:placed
    if @cart.save
      redirect_to pay_order_path(@cart)
    else
      flash.now[:danger]="Error processing cart"
      render 'checkout'
    end
  end

  private
    def cart_params
      params.require(:cart).permit(:postage_service_id, line_items_attributes: [:id, :product_id, :quantity, :_destroy])
    end

    def address_params
      params.require(:cart).permit(delivery_attributes: [:id, :source_address_id], billing_attributes: [:id, :source_address_id])
    end
end

app/helpers/cart_helper.rb
module CartHelper
  def current_cart
    begin
      @current_cart||=Cart.find_by_cart_token!(cookies[:cart_token]) if cookies[:cart_token]
    rescue ActiveRecord::RecordNotFound => exception
      cookies[:cart_token]=nil
    end
    @current_cart||=current_user.carts.first if signed_in? and current_user.carts.any?
    @current_cart||=Cart.new
  end

  def current_cart=(cart)
    if !cart.new_record? or cart.save
      cookies.permanent[:cart_token]=cart.cart_token
      cart
    else
      false
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    begin
      token=Rails.application.message_verifier(:cart_token).verify(cookies[:cart_token]) if !cookies[:cart_token].blank?
      @current_cart||=Cart.find_by_cart_token!(token) if token
    rescue ActiveRecord::RecordNotFound, ActiveSupport::MessageVerifier::InvalidSignature => exception
      self.current_cart=nil
    end
    @current_cart||=current_user.try(:carts).try(:first)
    @current_cart||=Cart.new(user: current_user)
    @current_cart=Cart.new(user: current_user) if @current_cart.user && !current_user?(@current_cart.user)
    @current_cart
  end

  def current_cart=(cart)
    if cart.nil?
      cookies.delete(:cart_token)
      @current_cart=cart
    elsif !cart.new_record? or cart.save
      cookies.permanent[:cart_token]=Rails.application.message_verifier(:cart_token).generate(cart.cart_token)
      @current_cart=cart
    else
      false
    end
  end

end

app/views/carts/_address_wrapper.html.erb
<div class="address_wrapper" id="<%= mode.to_s %>">
	<div class="address_picker">
		<%= form_for [:update_address, @cart], remote: true, html: {class: "form-inline"} do |f| %>
			<%= f.fields_for mode do |add| %>
				<%= add.label :source_address_id, mode.to_s.capitalize, class: "control-label" %>
				<div class="input-group">
					<%= add.collection_select :source_address_id, current_user.addresses, :id, :label, {prompt: true}, class: "form-control", data: { submit_on_change: true} %>
					<div class="input-group-btn">
						<%= f.submit "Select", class: "btn btn-default" %>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
	<address class="order_address">
		<% if address.try(:address) %>
			<% if !address.source_address.nil? and address.source_address.address!=address.address %>
			<div class="alert alert-warning">
			You have changed your address labelled <%= address.source_address.label %> since you created this order.  If you wish to update to the new address press 'Select' above.
			</div>
			<% end %>
			<%= simple_format address.address %>
		<% end %>
	</address>
</div>

app/views/carts/_cart_form.html.erb
<% if cart.line_items.any? %>
	<%= form_for cart, remote: true do |f| %>
        <%= render 'shared/form_error', object: f.object %>
		<%= render 'shared/order_header' %>
		<%= f.fields_for :line_items, include_id: false do |li| %>
			<div class="row">
				<%= render 'line_items/line_item_fields', f: li %>
				<% if li.object.persisted? %>
					<div class="cart_save_button">
						<div class="checkbox">
							<label>
								<%= li.check_box :_destroy, data: {submit_on_change: true} %> Remove
							</label>
						</div>
					</div>
				<% end %>
				<%= #Manually include the id here otherwise it gets added to end and breaks nth styling css
				li.hidden_field :id if !li.object.id.nil? %>
			</div>
		<% end %>
		<div class="row">
			<div class="cart_postage_cost_select">
				<div class="form-group">
					<%= f.label :postage_service, class: "control-label" %>
					<%= f.collection_select :postage_service_id, PostageService.all, :id, :name, {}, class: "form-control", data: {submit_on_change: true} %>
				</div>
			</div>
		</div>
		<%= render 'shared/order_footer', order: cart %>
		<div class="btn-group pull-right">
		    <%= link_to "Continue shopping", products_path, class: "btn btn-default" %>
		    <%= f.submit "Update basket", class: "btn btn-default" %>
		    <%= f.submit "Checkout", class: "btn btn-primary" %>
		</div>
	<% end %>

<% else %>
<%= content_tag(:h4, "Cart empty!") %>
<%= link_to "Go shopping", products_path, class: "btn btn-default" %>
<% end %>

app/views/carts/_table_footer.html.erb
</div>
<div class="row">
	<div class="cart_product">
	</div>
	<div class="cart_actions">
	</div>
	<div class="cart_line_item text-right">
		Total cost:
	</div>
	<div class="cart_line_cost text-right">
		<%= cost_to_currency(*@cart.try(:costs)) %>
	</div>
	<div class="clearfix"></div>
</div>
</div>

app/views/carts/_table_header.html.erb
<div>
    <div class="row cart_header">
		<div class="cart_product">
			Product
		</div>
		<div class="cart_actions">
			Quantity
		</div>
		<div class="cart_line_item text-right">
			Item cost
		</div>
		<div class="cart_line_cost text-right">
			Total cost
		</div>
		<div class="cart_save_button">
		</div>
	</div>
    <div class="cart_container">

app/views/carts/checkout.html.erb
<% provide(:title, "Checkout") %>

<%= content_tag(:h1, "Checkout") %>

<%= content_tag(:h4, "Please confirm the following order") %>

<%= content_tag(:h5, "Clicking confirm will take you to the payment page") %>

<%= render 'shared/form_error', object: @cart %>

<div class="row">
	<div class="col-md-offset-1 col-md-11">
		<%= link_to "Manage addresses", addresses_path, class: "btn btn-default" %>
	</div>
	<%= render 'address_wrapper', address: @cart.delivery, mode: :delivery %>
	<%= render 'address_wrapper', address: @cart.billing, mode: :billing %>
</div>

<%= render 'shared/order_header' %>

<%= render @cart.line_items %>

<%= render 'shared/order_footer', order: @cart %>

<div class="pull-right">
	<%= button_to "Confirm order", confirm_cart_path, method: :patch, class: "btn btn-primary btn_confirm" %>
</div>

app/views/carts/redirect_to_checkout.js.erb
<%= render 'shared/redirect_to', url: checkout_url %>

app/views/carts/show.html.erb
<% provide(:title, "View cart") %>

<%= content_tag(:h1, "Shopping cart") %>

<div id="cart">
	<%= render 'cart_form', cart: @cart %>
</div>

app/views/carts/show.js.erb
jQuery("#cart").html("<%= escape_javascript(render 'cart_form', cart: @cart) %>");
<%= render 'shared/refresh_cart_count' %>
<%= render 'shared/refresh_flash' %>

app/views/carts/update_address.js.erb
<% @modes.each do |mode,v| %>
<% actual_mode=mode.to_s.gsub("_attributes","").to_sym %>
jQuery("#<%= actual_mode %>").replaceWith("<%= escape_javascript( render 'address_wrapper', address: @cart.send(actual_mode), mode: actual_mode ) %>");
<% end %>
<%= render 'shared/refresh_flash' %>