config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  root 'products#index'

  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  resources :sessions, only: [:create]
  get '/signup' => 'users#new'
  get '/my_account' => 'users#edit'
  resource :user, only: [:create, :update] do
    member do
      get 'password'
      patch 'update_password'
      post 'update_password'
    end
  end

  concern :buyable do
    get 'buy' => 'line_items#new'
  end

  resources :charges, only: [:index, :show] do
    member do
      post 'refund'
      patch 'refund'
    end
  end

  resources :postage_services, except: [:show] do
    resources :postage_costs, only: [:new]
  end

  resources :products do
    concerns :buyable
    resources :stock_levels, only: [:index, :new, :create]
    resources :sub_products, only: [:index, :new]
    resources :allocations, only: [:index]
  end

  resources :gift_card_products, only: :index do
    concerns :buyable
  end

  resources :gift_card_products, only: :show, controller: :products

  resources :gift_cards, only: [:index] do
    collection do
      get :redeem
      post :allocate
      patch :allocate
    end
  end

  resources :stock_levels, only: [:destroy, :edit, :update] do
    resources :orders, only: [:index], module: :seller
    resources :allocations, only: [:index]
  end

  resources :allocations, only: [:index]

  resources :images, only: [:show]

  resources :orders, except: [:destroy, :new, :create, :edit] do
    member do
      patch 'set_current'
      get 'pay'
      patch 'cancel'
    end
    resources :redemptions, only: [:create, :destroy], shallow: true
  end
  resource :cart, only: [:show, :destroy, :update] do
    patch 'confirm'
    patch 'update_address'
  end
  resources :carts, only: [:index]
  get '/checkout' => 'carts#checkout'

  resources :line_items, only: [:show, :create, :destroy, :update]
  resources :currencies, except: :show

  resources :addresses
  resources :postage_costs, except: :show

  namespace :seller do
    get '/allocations/:allocation_id/gift_cards' => 'gift_cards#index', as: :allocation_gift_cards
    resources :orders, only: [:index, :show, :update] do
      resources :gift_cards, only: :index
    end
    resources :products, only: [:index]
    resources :gift_card_products, except: :show
    resources :gift_cards, except: :show do
      resources :orders, only: :index
    end
    resources :users, only: [:index] do
      resources :gift_cards, only: :new
      resources :orders, only: :index
      get '/allocations' => '/allocations#index'
    end
  end
  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  include Costable
  belongs_to :product, inverse_of: :line_items
  belongs_to :order, inverse_of: :line_items, counter_cache: true

  has_many :allocations, inverse_of: :line_item, dependent: :destroy

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :product, presence: true
  validates :order, presence: true
  validate :product_for_sale

  validates :product_id, uniqueness: {scope: :order_id, message: "already in order, update quantity and try again"}

  before_save :set_up_on_save


  def copy_cost_from_product
    #this will only run on cart/checkout so shouldn't change
    #after an order has been placed
    self.unit_cost=product.unit_cost
    self.currency=product.currency
    #return self for method chaining
    self
  end

  # find currency from product if none specified
  def currency
    super || product.try(:currency)
  end

  # find unit cost from product if none specified
  def unit_cost
    super || product.try(:unit_cost)
  end

  def cost
    unit_cost*quantity
  end

  def stock_check
    if product.stock_check(quantity)
      true
    else
      errors[:quantity]="is greater than current stock!"
      false
    end
  end

  def take_stock
    product.allocate_stock_to(self)
  end

  def release_stock
    allocations.destroy_all
  end

  def weight
    product.weight.to_f*quantity.to_i if product
  end

  private
    def set_up_on_save
      #by checking against status_was instead of status we'll allow saving of line_items when switching out of cart/checkout
      #if any of them are flagged as dirty
      errors[:base] << "Can't modify line item in non-cart states" and return false unless %w(cart checkout).include?(order.try(:status) || order.try(:status_was))
      copy_cost_from_product
      # Check currency of this product matches currency of the order
      errors[:base] << "Multi-currency orders currently unsupported" and return false unless self.currency==order.currency
    end

    def product_for_sale
      errors[:product]=I18n.t('errors.attributes.product.not_for_sale') if product and !product.for_sale?
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def new
    @product=Product.find(params[:product_id]) if params[:product_id]
    @product=GiftCardProduct.find(params[:gift_card_product_id]) if params[:gift_card_product_id]
    @line_item=current_cart.line_items.new(product: @product).copy_cost_from_product
    @stock_level=@product.stock_levels.current.first
    flash.now[:danger]=I18n.t('not_for_sale') unless @product.for_sale?
  end

  def create
    self.current_cart=current_cart if current_cart.save
    @line_item=current_cart.line_items.new(line_item_params)
    if request.xhr? and params[:submitted_from]=~/quantity/
      # if it's been submitted by changing the quantity we won't actually save the item
      render 'new'
    elsif @line_item.save
      # We've added a new line item, but the current_cart is still cached with the old value
      current_cart.reload
      flash.now[:success]="#{@line_item.product.name} added to cart"
      respond_to do |format|
        format.html { redirect_to products_path }
        format.js
      end
    else
      if current_cart.line_items.any? and @line_item_duplicate=current_cart.line_items.find_by(line_item_params.except(:quantity))
        @line_item_duplicate.errors[:product_id]=@line_item.errors[:product_id]
      else
        flash.now[:danger]="Error adding item to cart"
      end
      render 'new'
    end
  end

  def update
    @line_item=current_cart.line_items.find(params[:id])
    # if someone has changed the quantity, we'll just pretend to update
    if request.xhr? and params[:submitted_from]=~/quantity/
      # soft update without save
      @line_item.assign_attributes(line_item_params)
      # and refresh the display
      render 'new'
    elsif @line_item.update_attributes(line_item_params)
      flash.now[:success]="Cart updated"
      respond_to do |format|
        format.html { redirect_to products_path }
        format.js
      end
    else
      flash[:danger]="Cart item update failed"
      render 'new'
    end
  end

  private
    def line_item_params
      params.require(:line_item).permit(:product_id, :quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_line_item.html.erb
<div class="row cart_container">
	<div class="cart_product">
		<div class="cart_header">
			Product
		</div>
		<%= line_item.buyable.name %>
	</div>
	<div class="cart_actions">
		<div class="cart_header">
			Quantity
		</div>
		<%= line_item.quantity %>
	</div>
	<div class="cart_line_item text-right">
		<div class="cart_header">
			Item cost
		</div>
		<%= cost_to_currency(line_item.buyable) %>
	</div>
	<div class="cart_line_cost text-right">
		<div class="cart_header">
			Total cost
		</div>
		<%= cost_to_currency(line_item) %>
	</div>
</div>

app/views/line_items/_line_item_fields.html.erb
<div class="cart_product">
    <%= render 'shared/form_error', object: f.object %>
    <div class="cart_header">
    	Product
    </div>
	<div class="form-group">
		<label class="label-control"><%= f.object.buyable.name %></label>
		<% if @stock_level.try(:due_at) and @stock_level.due_at>DateTime.now %>
			<p class="help-block">This item is available for pre-order with stock due on <%= l(@stock_level.due_at.in_time_zone(t('time.zone')).to_date) %></p>
		<% end %>
	</div>
</div>
<div class="cart_actions form-group">
	<div class="cart_header">
		Quantity
	</div>
	<%= f.text_field :quantity, value: f.object.quantity, class: "form-control", data: {submit_on_change: true} %>
</div>
<div class="cart_line_item text-right">
	<div class="cart_header">
		Item cost
	</div>
	<%= cost_to_currency(f.object.buyable) %>
</div>
<div class="cart_line_cost text-right">
	<div class="cart_header">
		Total cost
	</div>
	<%= cost_to_currency(f.object) %>
</div>

app/views/line_items/_line_item_form.html.erb
<div class="row" id="<%=css_id(line_item_form)%>">
<% if line_item_form.buyable.sub_products.any? %>
	<div class="row">
		<div class="col-md-4">
			<%= render 'line_items/sub_product_choices', sub_products: line_item_form.buyable.sub_products %>
		</div>
	</div>
<% else %>
	<% if line_item_form.buyable.current_stock.available>0 %>
		<%= form_for line_item_form, remote: true, html: {class: "form-inline"} do |f| %>
			<% if f.object.errors.any? %>
				<%= render 'shared/form_error', object: f.object %>
			<% end %>
			<%= f.hidden_field :buyable_id %>
			<%= f.hidden_field :buyable_type %>
			<%= render 'line_items/line_item_fields', f: f %>
			<div class="row">
				<div class="cart_save_button pull-right">
					<%= f.submit "Add to cart", class: "btn btn-default" %>
				</div>
			</div>
		<% end %>
	<% else %>
		<%= line_item_form.buyable.name %> out of stock
	<% end %>
	<% if line_item_form.new_record? and line_item_form.buyable.master_product.present? %>
		<%= render 'line_items/sub_product_choices', sub_products: line_item_form.buyable.master_product.sub_products %>
	<% end %>
<% end %>
</div>

app/views/line_items/_sub_product.html.erb
<li>
	<%= link_to sub_product.name, product_buy_path(sub_product), remote: true %>
</li>

app/views/line_items/_sub_product_choices.html.erb
<div class="dropdown" class="sub_product_choices">
	<button type="button" id="subproduct-select" data-toggle="dropdown" class="btn btn-default">Please select <span class="caret"></span></button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="subproduct-select">
		<%= render partial: "line_items/sub_product", collection: sub_products %>
	</ul>
</div>

app/views/line_items/_table_header.html.erb
<div>
    <div class="row cart_header">
		<div class="cart_product">
			Product
		</div>
		<div class="cart_actions">
			Actions
		</div>
		<div class="cart_line_item text-right">
			Item cost
		</div>
		<div class="cart_line_cost text-right">
			Total cost
		</div>
		<div class="cart_save_button">
		</div>
        </div>
        <div class="cart_container">

app/views/line_items/create.js.erb
<%= render 'shared/refresh_flash' %>
<%= render 'shared/refresh_cart_count' %>
<% if params[:commit]=="Add to cart" %>
	<%= render 'shared/hide_modal' %>
<% else %>
	jQuery("#lineitem_new").replaceWith("<%= escape_javascript(render 'line_item_form', line_item_form: @line_item) %>");
<% end %>

app/views/line_items/new.html.erb
<% provide(:title, "Add item to cart") %>
<% provide(:modal_style, "modal-lg") %>

<%= render 'shared/order_header' %>
<%= render 'line_item_form', line_item_form: @line_item_duplicate || @line_item %>
<%= render 'shared/order_footer', order: @cart %>

app/views/line_items/new.js.erb
<%= render 'shared/refresh_flash' %>
jQuery("#<%= css_id(@line_item)%>").replaceWith("<%= escape_javascript(render 'line_item_form', line_item_form: @line_item_duplicate || @line_item) %>");
jQuery("#modal").attr("data-modal-ajax-current", "<%= url_for [@line_item.buyable, :buy] %>");

app/views/line_items/update.js.erb
<%= render 'shared/refresh_flash' %>
jQuery("#<%=css_id(@line_item) %>").replaceWith("<%= escape_javascript(render 'line_item_form', line_item_form: @line_item) %>");
<%= render 'shared/hide_modal' %>